---
- hosts: mywebservers 
  become: yes
  tasks:
    - name: Install tree package
      apt:
        name: tree
        state: present
    - name: install webserver on node side
      apt:
        name: apache2
        state: present
    - name: install git on node side
      apt:
        name: git
        state: present
    - name: Start web server on debian node
      service:
            name: apache2
            state: started
