---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
    - name: install webserver on RedHat node side
      yum:
        name: "{{ mywebpackredhat }}"
        state: present
    - name: Start web server on RedHat node side
      service:
        name: "{{ mywebpackredhat }}"
        state: started
    - name: install webserver on debion node side
      apt:
        name: "{{ mywebpackdebian }}"
        state: present
    - name: Start web server on Debian node side
      service:
        name: "{{ mywebpackdebian }}"
        state: started
          
